version: "3"
services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=sqlite3
      - GITEA__webhook__ALLOWED_HOST_LIST=172.22.144.2
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"
      - "222:22"
    restart: always
